# Generated by Django 4.1.1 on 2022-10-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatomodel',
            name='foto',
            field=models.ImageField(default=None, height_field=50, upload_to='static/fotos', width_field=50),
        ),
    ]
